# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PyInstaller

on:
  push:
    branches: [ master ]
  release:
    types: [created]

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools pyinstaller vk_api python3-anticaptcha requests

    - name: PyInstaller
      run: |
        pyinstaller --exclude-module _bootlocale --onefile core/spam.py --hidden-import=vk_api --hidden-import=python3-anticaptcha --hidden-import=requests

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        path: dist/spam.exe
        name: vk-spammer.exe
